baseURL = 'https://infinitegwei.github.io/too-on-chain/'
languageCode = 'en-us'
title = 'Too On-Chain'
theme = 'digitalgarden'

# googleAnalytics = "UA-PROPERTY_ID"

# [Params]
#   description = "My Digital Garden on the Internet"
#   images = ['/digital-garden-logo.png']
#   enableSearch = true

# [Params.newsletter]
#   title = ""
#   description = "A curated weekly digest once a week to your mailbox"

  # Supports buttondown, substack and revue
  # provider = "buttondown"

  # Buttondown - URL from share page; Refer: https://blog.buttondown.email/2019/10/11/adding-a-buttondown-subscription-form-to-webflow#getting-your-subscription-url
  # Substack - URL of the newsletter homepage; Example: https://on.substack.com/
  # Revue - Username
  # path = "https://buttondown.email/api/emails/embed-subscribe/"

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  url = '/content'  # Added URL here as an example
  weight = 2
[[menu.main]]
  name = 'Airdrops'
  url = '/airdrops'
  weight = 3
[[menu.main]]
  name = 'Deep Dives'
  url = '/deep-dives'
  weight = 4
[[menu.main]]
  name = 'Tokens'
  url = '/tokens'
  weight = 5
[[menu.main]]
  name = 'Info'
  url = '/info'  # Added URL here as an example
  weight = 6
[[menu.main]]
  name = 'Members'
  url = '/members'
  weight = 7
#[[menu.main]]
#  name = 'Contribute'
#  url = '/contribute'
#  weight = 8

# [[menu.main]]
#   name = 'Polywork'
#   url = 'https://polywork.com'
#   weight = 7
# [[menu.social]]
#   name = 'Twitter'
#   url = 'https://twitter.com'
#   weight = 1
[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/InfiniteGwei/too-on-chain'
  weight = 2
# [[menu.social]]
#   name = 'LinkedIn'
#   url = 'https://linkedin.com'
#   weight = 3
# [[menu.social]]
#   name = 'Instagram'
#   url = 'https://instagram.com'
#   weight = 4
# [[menu.social]]
#   name = 'Dribbble'
#   url = 'https://dribbble.com'
#   weight = 5
# [[menu.social]]
#   name = 'Codepen'
#   url = 'https://codepen.io'
#   weight = 6
# [[menu.social]]
#   name = 'Twitch'
#   url = 'https://twitch.com'
#   weight = 7
# [[menu.social]]
#   name = 'Email'
#   url = 'mailto:user@example.org'
#   weight = 8
# [[menu.social]]
#   name = 'RSS'
#   url = '/articles/index.xml'
#   weight = 9


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true